[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
axum = { version = "0.8.4", features = ["http2", "macros", "ws"] }
axum-extra = { version = "0.10.1", features = ["multipart"] }
bytes = "1.10.1"
chrono = "0.4.41"
cors = "0.1.0"
futures-util = "0.3.31"
itertools = "0.14.0"
log = "0.4.27"
multipart = "0.18.0"
ordered-float = "5.0.0"
process_mining = "0.3.25"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
simplelog = "0.12.2"
tokio = { version = "1.46.1", features = ["full"] }
tower-http = { version ="0.6.6", features = ["cors"] }
uuid = "1.17.0"


